# Configuration of Hugo
# Guide: https://wowchemy.com/docs/getting-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: Idaho Ag Stats # Website name
baseurl: '' # Website URL
copyright: 'Copyright @ {year} by the [University of Idaho Statistical Programs](https://www.uidaho.edu/cals/statistical-programs). <br> Built with [Wowchemy](https://wowchemy.com/), a free open-source web builder.' 
    # Footer text, e.g. '© {year} Me'
    

############################
## custom stuff for rss feed
############################ 
outputFormats:
  outputFormats.RSS:
    baseName: 'rss'

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## MODULES
############################

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy

############################
## ADVANCED
############################
rssLimit: 50
enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  #event: '/talk/:slug/'
  #authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  #publication_types: '/publication-type/:slug/'
disableAliases: true
outputs:
  home: [HTML, JSON, WebAppManifest, headers, redirects]
  section: [HTML]
  page: [HTML, RSS]
  taxonomyTerm: [HTML]
  taxonomy: [HTML]
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: false
  tableOfContents:
    startLevel: 2
    endLevel: 3
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  #publication_type: publication_types
  author: authors
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70

