# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.



[[main]]
  name = "Tutorials"
  parent = "Tutorials"
  url = "tutorials"
  weight = 10
  
[[main]]
  name = "R"
  parent = "Tutorials"
  url = "tutorials/r"
  weight = 11
  
[[main]]
  name = "SAS"
  parent = "Tutorials"
  url = "tutorials/sas"
  weight = 12
  
[[main]]
  name = "General Ag Stats"
  parent = "Tutorials"
  url = "tutorials/stats"
  weight = 12

[[main]]
  name = "Blog"
  url = "blog"
  weight = 30
  
[[main]]
  name = "Workshops"
  url = "workshops"
  weight = 40

[[main]]
  pre = "<i class='fa fa-rss'></i>"
  url =  "index.xml"
  target="_blank"
  weight = 80

