theme = "starter-academic"
baseURL = "/"
#http://example.org/"
languageCode = "en-us"
title = "University of Idaho Agricultural Statistics"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
